export const CART_EVENT = {
  ADD: "ADD",
  REMOVE: "REMOVE",
  UPDATE_QTY: "UPDATE_QTY",
  SAVE_FOR_LATER: "SAVE_FOR_LATER",
  PAY: "PAY"
};
export const SAVE_FOR_LATER_EVENT = {
  ADD_TO_LIST: "ADD_TO_LIST",
  UNSAVE: "UNSAVE",
  MOVE_TO_CART: "MOVE_TO_CART"
};
